spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      host: mongo
      port: 27017
      database: scoober

server:
  port: 8080

logging:
  level:
    "[org.springframework.kafka]": DEBUG